### ISSUE TITLE
Navigation component crashes.

### ISSUE THREAD

**Issue by KoTius** [googlesamples/android-sunflower#239]
I guess this is just broken Navigation, and i'm going to post this issue at Navigation bug tracker but still.

1. Open Plant list screen
2. With 2 or more fingers tap different Plant items at the same time
3. You will get exception

> java.lang.IllegalArgumentException: navigation destination com.google.samples.apps.sunflower:id/action_plant_list_fragment_to_plant_detail_fragment is unknown to this NavController

Seems like after first click Navigation framework thinks you are already at Plant detail part of the nav graph. And this fragment can't use this action.
It seems just broken as for me. I'd like it opens two separate screens if you do things like this.
This probably will crash you app everywhere when you can navigate with more then 1 then click listener (for example 2 buttons to register/forgot password screens)

In the current situation i have found few workarounds with this problem:
1. We can wrap `it.findNavController().navigate(direction)` with tryCatch block, catch IllegalArgumentException and do nothing. But it seems just broken, don't forget to leave a commentary in that catch block
2. You can use Global actions only https://developer.android.com/topic/libraries/architecture/navigation/navigation-global-action
But this is again will look just horrible tho. This seems acceptable if we add search into the app
3. You can add to PlantDetailFragment in nav graph action to navigate to itself (recursive). This is horrible as well. 

Offtopic: if you use recursive destination and tie ActonBar with NavController - check you home/back button. This will be broken if your recursive destination is first in nav graph.

Well, i don't have the good looking solution for the issue quite yet. Still working

UPD: Copy of this bug at google tracker https://issuetracker.google.com/issues/118975714

**Comment by XinyueZ** [comment]
@KoTius have you tried #238 and reproduced this version which is already updated by the newest version of nav-lib and I have adjusted something there?

**Comment by tiembo** [comment]
@KoTius thanks for reporting this issue.  I can reproduce it even with with the changes in #238.  It's a good idea to create a bug in the navigation tracker, too.

**Comment by KoTius** [comment]
@tiembo i did it. Updated first post

**Comment by tiembo** [comment]
@KoTius Thanks!

**Comment by tiembo** [comment]
@KoTius thanks for the update.  Are you interested in opening a PR with a fix for this issue?

**Comment by KoTius** [comment]
@tiembo Guess so. Never made PR tho.

**Comment by KoTius** [comment]
I have not figured out yet how do androidx artifacts work.
Changelog as a google dev says that it fixed in  androidx.fragment 1.1.0-alpha01.
I though it would be enough to set androidx.appcompat:appcompat version to 1.1.0-alpha01. It includes the fragment artifact, isn't it?
I did it and i can see other changes from changelog for this version (like: Significantly expanded the nullability annotations across the Fragment API surface.). But the app still crashes.

**Comment by tiembo** [comment]
Hi @KoTius - thanks for following up.  I'm looking more into this.

**Comment by tiembo** [comment]
Closing this bug, as unfortunately there's nothing that can be done at the library level, much less in the Sunflower code, to fix this issue.

**Comment by IgorGanapolsky** [comment]
I am getting the same issue with **java.lang.IllegalStateException: no current navigation node**

**Comment by opengamer29** [comment]
Hello all. We are thinking about using google navigation in our app and I'm really worried about this issue. As I can see it's still reproducible in my pet project.
Do you have any additional info about this issue? Maybe link to issue inside library issue tracker?

**Comment by opengamer29** [comment]
I was able to find only this answer on StackOverflow, but it looks only like workaround, not a stable solution:

`fun NavController.navigateSafe(direction: NavDirections) {
    currentDestination?.getAction(direction.actionId)?.let { navigate(direction) }
}`

https://stackoverflow.com/questions/59633075/double-click-on-view-recycler-item-causes-illegalargumentexception-navigation

**Comment by Zhuinden** [comment]
@opengamer29 you could try a different navigation library that can also make navigation from one screen to another an actual one-liner, and wouldn't crash from tapping two plants at once https://github.com/Zhuinden/simple-stack-tutorials/blob/534a2c63a6827bbfd3179ac2d2dd75d863dd843e/app/src/main/java/com/zhuinden/simplestacktutorials/steps/step_5/Step5FirstFragment.kt#L19

**Comment by gobasktproductengineering** [comment]
> @opengamer29 you could try a different navigation library that can also make navigation from one screen to another an actual one-liner, and wouldn't crash from tapping two plants at once
> 
> See https://github.com/Zhuinden/simple-stack-tutorials/blob/534a2c63a6827bbfd3179ac2d2dd75d863dd843e/app/src/main/java/com/zhuinden/simplestacktutorials/steps/step_5/Step5FirstFragment.kt#L19

Thanks a lot man. you just saved me.

**Comment by dvrajput96** [comment]
> @opengamer29 you could try a different navigation library that can also make navigation from one screen to another an actual one-liner, and wouldn't crash from tapping two plants at once
> 
> See https://github.com/Zhuinden/simple-stack-tutorials/blob/534a2c63a6827bbfd3179ac2d2dd75d863dd843e/app/src/main/java/com/zhuinden/simplestacktutorials/steps/step_5/Step5FirstFragment.kt#L19

Thanks a lot man, You just saved my day.
